name: vinsartisanmarket
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  get: ^4.6.1
  shared_preferences: ^2.0.13
  google_nav_bar: ^5.0.5
  loading_indicator: ^3.0.3
  google_fonts: ^2.2.0
  icon_badge: ^1.0.0
  youtube_player_flutter: ^8.0.0
  carousel_slider: ^4.0.0
  url_launcher: ^6.0.6
  file_picker: ^4.2.8
  lottie: ^1.1.0
  http: ^0.13.4
  connectivity_plus: ^1.0.6
  path_provider: ^2.0.3
  is_first_run: ^1.0.0
  sqflite: ^2.0.0+4
  path: ^1.8.0
  fluttertoast: ^8.0.8
  flutter_svg: ^0.22.0
  image_picker: ^0.8.3+3
  double_back_to_close: ^2.0.0
  flutter_local_notifications: ^6.0.0
  awesome_dialog: ^2.1.0
  fab_circular_menu: ^1.0.2
  rflutter_alert: ^2.0.1
  line_icons: ^2.0.1
  introduction_screen: ^3.0.0
  cached_network_image: ^3.2.0
  flutter_paypal: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  change_app_package_name: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/appLogo.png"
  
  

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - assets/images/
    - assets/icons/
    - assets/animation/

